// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 4
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){

var O=this,va=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},wa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},xa=null;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ya=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,za=function(a){if(null==a)return String(a);var b=ya.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Aa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},da=function(a){if(!a||"object"!=za(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Aa(a,"constructor")&&!Aa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return void 0===
c||Aa(a,c)},Ba=function(a,b){var c=b||("array"==za(a)?[]:{}),d;for(d in a)if(Aa(a,d)){var e=a[d];"array"==za(e)?("array"!=za(c[d])&&(c[d]=[]),c[d]=Ba(e,c[d])):da(e)?(da(c[d])||(c[d]={}),c[d]=Ba(e,c[d])):c[d]=e}return c};var Ca=Math.random(),Ea=null,Fa=null,Ga={};var Ha=function(){},I=function(a){return"function"==typeof a},R=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Ia=function(a){return"number"==za(a)&&!isNaN(a)},Ja=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},La=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},J=function(a){return Math.round(Number(a))||0},fa=function(a){return"false"==String(a).toLowerCase()?!1:
!!a},Ma=function(a){var b=[];if(R(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},B=function(){return new Date},Na=function(a,b){if(!Ia(a)||!Ia(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},Oa=function(){this.prefix="gtm.";this.values={}};Oa.prototype.set=function(a,b){this.values[this.prefix+a]=b};Oa.prototype.get=function(a){return this.values[this.prefix+a]};Oa.prototype.contains=function(a){return void 0!==this.get(a)};
var Pa=function(a,b,c){try{return a["3"](a,b||Ha,c||Ha)}catch(d){}return!1},Qa=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=La(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Ra=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Sa=function(a){for(var b=0;b<a.length;b++)a[b]()},ba=B().getTime(),ea=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ta=function(a,
b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},Ua=function(a){return null!==a&&void 0!==a&&void 0!==a.length},ca=function(a,b,c){if(!(b&&c&&Ua(a)&&R(a)&&0!=a.length))return null;for(var d={},e=0;e<a.length;e++)a[e]&&a[e].hasOwnProperty(b)&&a[e].hasOwnProperty(c)&&(d[a[e][b]]=a[e][c]);return d},Va=function(a,b){0==b?a.Ca=!0:a.complete=!0;var c=a.f;a.g&&(a.g.ca[c]=b);Ga[c]&&(Ga[c].state=b)};var A=window,N=document,Xa=navigator,v=function(a,b,c){var d=A[a];if(a&&/^[a-zA-Z_]\w*$/g.test(a)){var e="var "+a+";";if(O.execScript)O.execScript(e,"JavaScript");else if(O.eval){if(null==xa)if(O.eval("var _evalTest_ = 1;"),"undefined"!=typeof O._evalTest_){try{delete O._evalTest_}catch(f){}xa=!0}else xa=!1;if(xa)O.eval(e);else{var g=O.document,h=g.createElement("SCRIPT");h.type="text/javascript";h.defer=!1;h.appendChild(g.createTextNode(e));g.body.appendChild(h);g.body.removeChild(h)}}else throw Error("goog.globalEval not available");
}A[a]=void 0===d||c?b:d;return A[a]},K=function(a,b,c,d){return(d||"http:"!=A.location.protocol?a:b)+c},Ya=function(a){var b=N.getElementsByTagName("script")[0]||N.body||N.head;b.parentNode.insertBefore(a,b)},ha=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},p=function(a,b,c){var d=N.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;ha(d,b);c&&(d.onerror=c);Ya(d)},na=function(a,
b){var c=N.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Ya(c);ha(c,b);void 0!==a&&(c.src=a);return c},M=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},T=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},q=function(a){A.setTimeout(a,0)},ja=!1,ka=[],Za=function(a){if(!ja){var b=N.createEventObject,c="complete"==
N.readyState,d="interactive"==N.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ja=!0;for(var e=0;e<ka.length;e++)ka[e]()}}},$a=0,ab=function(){if(!ja&&140>$a){$a++;try{N.documentElement.doScroll("left"),Za()}catch(a){A.setTimeout(ab,50)}}},cb=function(a){var b=N.getElementById(a);if(b&&bb(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(bb(document.all[a][c],"id")==a)return document.all[a][c];return b},bb=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:
null},db=function(a){return a.target||a.srcElement||{}},oa=function(a){var b=N.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},eb=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},fb=!1,gb=[],hb=function(){if(!fb){fb=!0;for(var a=0;a<gb.length;a++)gb[a]()}},ib=
function(a){a=a||A;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},la=function(a){window.console&&window.console.log&&window.console.log(a)};var jb=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||A.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||A.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:A.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=Ja(d||[],l[l.length-
1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),k=0;k<m.length;k++){var n=m[k].split("=");if(decodeURIComponent(n[0]).replace("+"," ")==e){var r=n.slice(1).join("=");f=decodeURIComponent(r).replace("+"," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},kb=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},qa=function(a){var b=N.createElement("a");
a&&(b.href=a);return b};var ra=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=jb(qa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},ta=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var sa=function(a,b){p("//bat.bing.com/bat.js",a,b)},L=A,ga=function(a,b,c){b&&(void 0===L[a]||c&&!L[a])&&(L[a]=b);return L[a]};var mb=new Oa,nb={},qb={set:function(a,b){Ba(ob(a,b),nb)},get:function(a){return G(a,2)},reset:function(){mb=new Oa;nb={}}},G=function(a,b){if(2==b){for(var c=nb,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return mb.get(a)},ob=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var rb=new RegExp(/^(.*\.)?(google|youtube|blogger)(\.com?)?(\.[a-z]{2})?\.?$/),sb={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},tb={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},ub=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},vb=function(){var a=G("gtm.whitelist");
var b=a&&ub(Ma(a),sb),c=G("gtm.blacklist")||G("tagTypeBlacklist")||[];rb.test(A.location&&A.location.hostname)&&(c=Ma(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&ub(Ma(c),tb),e={};return function(f){var g=f&&f["3"];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>Ja(b,g.a))if(g.b&&0<g.b.length)for(var l=0;l<g.b.length;l++){if(0>
Ja(b,g.b[l])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var k;if(!(k=0<=Ja(d,g.a)))a:{for(var n=g.b||[],r=new Oa,u=0;u<d.length;u++)r.set(d[u],!0);for(u=0;u<n.length;u++)if(r.get(n[u])){k=!0;break a}k=!1}m=k}return e[g.a]=!h||m}};var S=function(a){var b=N;return wb?b.querySelectorAll(a):null},xb;a:{var yb=/MSIE +([\d\.]+)/.exec(Xa.userAgent);if(yb&&yb[1]){var zb=N.documentMode;zb||(zb="CSS1Compat"==N.compatMode?parseInt(yb[1],10):5);if(!zb||8>=zb){xb=!1;break a}}xb=!!N.querySelectorAll}var wb=xb;var Ab=void 0,Bb="",Cb=0,Db=void 0,_et=function(a){var b,c=G("gtm.element"),d=G("event"),e=Number(B());if(Ab===c&&Bb===d&&Cb>e-250)b=Db;else{var f;if(c){var g=c.innerText||c.textContent||"";g&&" "!=g&&(g=g.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));g&&(g=g.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));f=g}else f="";Db=b=f;Ab=c;Bb=d}Cb=e;return b?b:a[""]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(G("gtm.elementUrl")||a[""]||""),c=qa(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Fa};_e.a="e";_e.b=["google"];var _j=function(a){for(var b=String(a["6"]).split("."),c=A,d=0;d<b.length;d++)c=c&&c[b[d]];return c};_j.a="j";_j.b=["google"];var _v=function(a){var b=G(a["6"].replace(/\\\./g,"."),a[""]);return void 0!==b?b:a[""]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(G("gtm.referrer")||N.referrer);if(!b)return b;var c=qa(b);return b};_f.a="f";_f.b=["google"];var ua=function(a){var b=A.location,c=b.hash?b.href.replace(b.hash,""):b.href,d;if(d=a[""]?a[""]:G("gtm.url"))c=String(d),b=qa(c);var e,f,g;
a["2"]&&(c=jb(b,a["2"],e,f,g));return c},_u=ua;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a["0"])==String(a["1"])};_eq.a="eq";_eq.b=["google"];var Kb=Math.random(),Lb="1.000000">Kb;var Mb=Ha;var Nb=Ha,Ob=[],Rb=!1,Sb=function(a){return A["dataLayer"].push(a)},Xb=function(a){var b=!1;return function(){!b&&I(a)&&q(a);b=!0}},cc=function(){for(var a=!1;!Rb&&0<Ob.length;){Rb=!0;var b=Ob.shift();if(I(b))try{b.call(qb)}catch(c){}else if(R(b))a:{var d=b;if("string"==za(d[0])){for(var e=d[0].split("."),f=e.pop(),g=d.slice(1),h=nb,l=0;l<e.length;l++){if(void 0===h[e[l]])break a;h=h[e[l]]}try{h[f].apply(h,g)}catch(m){}}}else{var k=b,n=void 0;for(n in k)if(k.hasOwnProperty(n)){var r=n,u=k[n];
mb.set(r,u);Ba(ob(r,u),nb)}var z=!1,t=k.event,x=void 0;if(t){x=ba++;Fa=t;if(!k["gtm.uniqueEventId"]){var E=x;mb.set("gtm.uniqueEventId",E);Ba(ob("gtm.uniqueEventId",E),nb)}var F=Xb(k.eventCallback),D=k.eventTimeout;D&&A.setTimeout(F,Number(D));z=Nb(x,t,F,k.eventReporter)}Ea||(Ea=k["gtm.start"])&&Mb();var w=k,C=x,y=t,H=nb;if(!z){var X=x,V=t;}Fa=null;a=z||a}var Da=b,aa=nb;bc();Rb=!1}return!a};var dc,ec=/(Firefox\D28\D)/g.test(Xa.userAgent),fc={nwnc:{},nwc:{},wnc:{},wc:{},wt:null,l:!1},gc={nwnc:{},nwc:{},wnc:{},wc:{},wt:null,l:!1},mc=function(a,b){return function(c){c=c||A.event;var d=db(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=eb(d,["a","area"]),e=!d||!d.href||hc(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?gc:fc;if(c.defaultPrevented||!1===c.returnValue||c.ga&&c.ga()){if(d){var g={simulateDefault:!1},
h=ic(f,["wnc","nwnc"]);h&&jc(a,d,g,f.wt,h)}}else{if(d){var g={},l=!0,m=ic(f,["wnc","nwnc","nwc","wc"]);(l=jc(a,d,g,f.wt,m))||(kc(g.eventReport,f)?b=!0:e=!0);e=e||l||"LINK_CLICK"==a&&ec;g.simulateDefault=!l&&b&&!e;g.simulateDefault&&(e=lc(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=l||!b||e;return c.returnValue}return!0}}}},jc=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||bb(b,"id")||"","gtm.elementTarget":b.formTarget||
b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=nc(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=oc(b);g.eventTimeout=f;g.eventCallback=pc(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=b.formAction||b.action||b.href||b.src||b.code||b.codebase||
"";break;default:return!0}return Sb(g)},oc=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},qc=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},lc=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Xa.userAgent),e=qc(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=A.frames&&A.frames[f]||A[f];break;case "_blank":d?(b.simulateDefault=
!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+B().getTime(),b.targetWindow=A.open("",b.targetWindowName));break;default:d&&!A.frames[e]?(b.simulateDefault=!1,c=!0):(A.frames[e]||(b.targetWindowName=e),b.targetWindow=A.frames[e]||A.open("",e))}return c},nc=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||B().getTime(),500>B().getTime()-c&&A.setTimeout(nc(a,b,c),25)))}},pc=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;
b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);N.gtmSubmitFormNow=!0;rc(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||B().getTime(),500>B().getTime()-c&&A.setTimeout(pc(a,b,c),25)}},ic=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},sc=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},kc=function(a,b){if(b.wnc["0"]||
b.wc["0"])return!0;for(var c=0;c<tc.length;c++)if(a.passingRules[c]){var d=tc[c],e=uc[c],f=e&&e[0]&&e[0][0]||e[1]&&e[1][0];if(f&&"0"!=f&&(b.wc[f]||b.wnc[f]))for(var g=d[1],h=0;h<g.length;h++)if(a.resolvedTags[g[h]])return!0}return!1},vc=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(N.gtmHasClickListenerTag)return;N.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=db(a);b&&jc("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!dc&&(dc=kb(N.location));sc(fc,b||!1,c||!1,d,e);if(N.gtmHasLinkClickListenerTag)return;
N.gtmHasLinkClickListenerTag=!0;f="click";g=mc(a,b||!1);break;case "FORM_SUBMIT":sc(gc,b||!1,c||!1,d,e);if(N.gtmHasFormSubmitListenerTag)return;N.gtmHasFormSubmitListenerTag=!0;f="submit";g=mc(a,b||!1);break;default:return}T(N,f,g,h)},hc=function(a){if(!dc)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=qa(a);return dc==kb(c)},rc=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
N.gtmFormElementSubmitter||(N.gtmFormElementSubmitter=N.createElement("form"));return N.gtmFormElementSubmitter.submit.call?N.gtmFormElementSubmitter.submit:a.submit};var Eb=new String("undefined"),Ec=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Eb?b:a[d]);return c.join("")}};Ec.prototype.toString=function(){return this.resolve("undefined")};Ec.prototype.valueOf=Ec.prototype.toString;var Fc={},Gc=function(a,b){var c=ba++;Fc[c]=[a,b];return c},Hc=function(a){var b=a?0:1;return function(a){var d=Fc[a];if(d&&I(d[b]))d[b]();Fc[a]=void 0}};var Ic=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Oc=function(a,b){return a<b?-1:a>b?1:0};var Pc=function(a){var b=arguments.length;if(1==b&&"array"==va(arguments[0]))return Pc.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};Pc("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Qc;a:{var Uc=O.navigator;if(Uc){var Vc=Uc.userAgent;if(Vc){Qc=Vc;break a}}Qc=""}var U=function(a){return-1!=Qc.indexOf(a)};var Wc=U("Opera")||U("OPR"),Xc=U("Trident")||U("MSIE"),Yc=U("Edge"),Zc;if(Zc=U("Gecko"))Zc=!(-1!=Qc.toLowerCase().indexOf("webkit")&&!U("Edge"));var $c=Zc&&!(U("Trident")||U("MSIE"))&&!U("Edge"),ad=-1!=Qc.toLowerCase().indexOf("webkit")&&!U("Edge");ad&&U("Mobile");U("Macintosh");U("Windows");U("Linux")||U("CrOS");var bd=O.navigator||null;bd&&(bd.appVersion||"").indexOf("X11");U("Android");!U("iPhone")||U("iPod")||U("iPad");U("iPad");
var cd=function(){var a=Qc;if($c)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Yc)return/Edge\/([\d\.]+)/.exec(a);if(Xc)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ad)return/WebKit\/(\S+)/.exec(a)},dd=function(){var a=O.document;return a?a.documentMode:void 0},ed=function(){if(Wc&&O.opera){var a=O.opera.version;return"function"==va(a)?a():a}var b="",c=cd();c&&(b=c?c[1]:"");if(Xc){var d=dd();if(d>parseFloat(b))return String(d)}return b}(),fd={},gd=function(a){var b;if(!(b=fd[a])){for(var c=0,d=Ic(String(ed)).split("."),
e=Ic(String(a)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var n=m.exec(h)||["","",""],r=k.exec(l)||["","",""];if(0==n[0].length&&0==r[0].length)break;c=Oc(0==n[1].length?0:parseInt(n[1],10),0==r[1].length?0:parseInt(r[1],10))||Oc(0==n[2].length,0==r[2].length)||Oc(n[2],r[2])}while(0==c)}b=fd[a]=0<=c}return b},hd=O.document,id=hd&&Xc?dd()||("CSS1Compat"==hd.compatMode?parseInt(ed,10):5):void 0;var jd;if(!(jd=!$c&&!Xc)){var kd;if(kd=Xc)kd=9<=id;jd=kd}jd||$c&&gd("1.9.1");Xc&&gd("9");var ld=function(a){ld[" "](a);return a};ld[" "]=function(){};var ma=function(a,b){var c="";Xc&&!md(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(nd)a.srcdoc=d;else if(od){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else pd(a,d)},nd=ad&&"srcdoc"in document.createElement("iframe"),od=$c||ad||Xc&&gd(11),pd=function(a,b){Xc&&gd(7)&&!gd(10)&&6>qd()&&rd(b)&&(b=sd(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Xc&&!md(a)?td(a,c):c()},qd=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},md=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{ld(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(f){b=!1}return b}catch(g){return!1}},ud=0,td=function(a,b){var c="goog_rendering_callback"+ud++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},rd=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},sd=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var wd=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=wd(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=N.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,ha(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var l=[];e.firstChild;)l.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);wd(e,l,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(m){q(d)}}};var yd=function(a,b,c){if(N.body){var d=a["4"];d instanceof Ec&&(d=
d.resolve(Gc(b,c)),b=Ha);if(a[""])try{ma(na(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),q(b)}catch(e){q(c)}else a[""]?xd(d,b,c):wd(N.body,oa(d),b,c)()}else A.setTimeout(function(){yd(a,b,c)},200)},_html=yd;_html.a="html";_html.b=["customScripts"];var zd={},Bd=function(a,b,c,d,e){if(!wb)return!1;var f=zd[a];f||(f={id:a,G:[],T:0,qa:null,va:!1},zd[a]=f);var g={id:a+":"+f.G.length,Ka:c,Fa:d,F:b,ea:0,ba:e||null,ua:0,S:!1};f.G.push(g);null===b?(g.S=!0,c(null)):Ad(f);return!0},Ad=function(a){for(var b=a.T;b<a.G.length;b++){var c=a.G[b],d=b==a.T;if(!c.S&&!Cd(d,c))break;c.S&&d&&a.T++}a.G.length>a.T&&(a.qa||(a.qa=A.setTimeout(function(){a.qa=null;Ad(a)},80)),ja||a.va||(a.va=!0,ka.push(function(){Ad(a)})))},Cd=function(a,b){var c=[];if(b.F){var d=Dd(b.F,
b.id),e=null;b.ba&&(e=Dd(b.ba,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ja&&(null===b.ba.i||b.ua+c.length<b.ba.i)))break;c.push({element:g,kb:h})}}if(!ja&&b.Fa&&(!a||null==b.F.i||b.F.i!=b.ea+c.length))return!1;for(var l=0;l<c.length;l++){var m=c[l].element,k=c[l].kb;b.ea++;Ed(m,b.id);k&&(b.ua++,Ed(k,b.id+"-t"));b.Ka(m,k)}if(b.F.i&&b.F.i==b.ea||ja)b.S=!0;return!0},Ed=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=
!0},Dd=function(a,b){for(var c=S(a.o)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){var g;if(g=a.s){var h;a:{for(var l=f;l;){if(l.nextSibling){h=!0;break a}l=l.parentNode}h=!1}g=!h}if(g)break;d.push(f)}}return d};var Rd,Sd;
var be=function(a){return function(){}},ce=function(a){return function(){}};var te=function(a){var b=A||O,c=b.onerror,d=!1;ad&&!gd("535.3")&&(d=!d);b.onerror=function(b,f,g,h,l){c&&c(b,f,g,h,l);a({message:b,fileName:f,bb:g,Ab:h,error:l});return d}};
var W=[],ve={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},we=function(a){return ve[a]},xe=/[\x00\x22\x26\x27\x3c\x3e]/g;var Be=/[\x00\x08-\x0d\x22\x26\x27\/\x3c-\x3e\\\x85\u2028\u2029]/g,Ce={"\x00":"\\x00","\b":"\\x08","\t":"\\t","\n":"\\n","\x0B":"\\x0b","\f":"\\f",
"\r":"\\r",'"':"\\x22","&":"\\x26","'":"\\x27","/":"\\/","<":"\\x3c","=":"\\x3d",">":"\\x3e","\\":"\\\\","\u0085":"\\x85","\u2028":"\\u2028","\u2029":"\\u2029",$:"\\x24","(":"\\x28",")":"\\x29","*":"\\x2a","+":"\\x2b",",":"\\x2c","-":"\\x2d",".":"\\x2e",":":"\\x3a","?":"\\x3f","[":"\\x5b","]":"\\x5d","^":"\\x5e","{":"\\x7b","|":"\\x7c","}":"\\x7d"},De=function(a){return Ce[a]};
W[8]=function(a){if(null==a)return" null ";switch(typeof a){case "boolean":case "number":return" "+a+" ";default:return"'"+String(String(a)).replace(Be,De)+"'"}};
var Te=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Ue={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13",
"\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89",
"\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB","\uff3d":"%EF%BC%BD"},Ve=function(a){return Ue[a]};W[16]=function(a){return a};var Xe=53,Ye=[],Ze=[],$e=[],af=new Oa,bf=[],Y=[],tc=[],uc=[],cf=function(){this.v=[]};cf.prototype.set=function(a,b){this.v.push([a,b]);return this};cf.prototype.resolve=function(a,b){for(var c={},d=0;d<this.v.length;d++){var e=df(this.v[d][0],a,b),f=df(this.v[d][1],a,b);c[e]=f}return c};var ef=function(a){this.index=a};
ef.prototype.resolve=function(a,b){var c=$e[this.index];if(c&&!b(c)){var d=c["5"];if(a){if(a.get(d))return;a.set(d,!0)}c=df(c,a,b);a&&a.set(d,!1);return Pa(c)}};
var _M=function(a){return new ef(a)},ff=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=df(Ye[a[f]],b,c);g===Eb&&(e=!0);d.push(g)}return e?new Ec(d):d.join("")}},_T=function(a){return new ff(arguments)},gf=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=
function(c,d){var e=df(a[0],c,d);if(a[0]instanceof ef&&b(8)&&b(16)){if(e===Eb)return e;var f="gtm"+ba++;af.set(f,e);return'google_tag_manager["GTM-PT44P2"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=W[a[g]](e);return e}},_E=function(a,b){return new gf(arguments)},hf=function(a,b){this.j=a;this.aa=b},_R=function(a,b){return new hf(a,b)},jf=function(a,b){return df(a,new Oa,b)},df=function(a,b,c){var d=a;if(a instanceof ef||a instanceof cf||a instanceof ff||a instanceof gf)return a.resolve(b,
c);if(!(a instanceof hf))if(R(a))for(var d=[],e=0;e<a.length;e++)d[e]=df(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=df(a[f],b,c))}return d},kf=function(a,b){var c=b[a],d=c;if(c instanceof ef||c instanceof gf||c instanceof ff||c instanceof hf)d=c;else if(R(c))for(var d=[],e=0;e<c.length;e++)d[e]=kf(c[e],b);else if("object"==typeof c){var d=new cf,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],kf(c[f],b))}return d},mf=function(a,b){for(var c=b?b.split(","):
[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=Ye[e[1]]);if(1==a)for(var f=lf(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Ze[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=lf(e[g]);3==a&&(c[d]=Ye[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var l=0;l<e[g].length;l++)e[g][l]=Ye[e[g][l]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},lf=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Xe;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f=0,f=65<e&&90>=
e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},nf=function(a,b,c){a.push.apply(a,mf(b,c))};
var ac=function(){},vf=function(a){},bc=function(){},wf=function(a){},xf=function(a,b){},Zb=function(a){};var yf=function(a){var b=this;this.f=a;this.complete=this.Ca=!1;this.Z=[];this.R=[];this.J=function(){if(b.g&&b.g.event){var a=b.g.event,d=b.f;}b.complete||Sa(b.Z);Va(b,1)};this.I=function(){if(b.g&&b.g.event){var a=b.g.event,d=b.f;}b.complete||Sa(b.R);Va(b,2)};this.m=Ha},zf=function(a,b){a.Z.push(b)},
Af=function(a,b){a.R.push(b)},Bf=function(a){this.w=[];this.pa=[];this.wa={};this.ka=[];this.H=0;this.Aa={};this.Da={};this.ca={};this.event=a};Bf.prototype.addListener=function(a){this.ka.push(a)};
var Cf=function(a,b,c,d,e,f){if(!c.complete){a.w[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=R(d)?d.slice():["or",d];e=R(e)?e.slice():[e];f=R(f)?f.slice():[f];a.wa[b]=d;a.Aa[b]=0<e.length;a.Da[b]=0<f.length;a.H++;var g=function(){0<a.H&&a.H--;0<a.H||Sa(a.ka)};zf(c,g);Af(c,g)}},Df=function(a,b,c){a.w[b]&&(zf(a.w[b],function(){c(b,!0)}),Af(a.w[b],function(){c(b,!1)}))},Ef=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof hf&&a[g].j===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},If=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Y[b];if(a.event.c(h)){}else g=Ff(h,b,a);if(f=g){var k=Gf(b,!0);0<k.length&&e(k[0].j);c.push(f);var l=Gf(b,!1);0<l.length&&e(l[0].j)}else d=!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Gf(g.f,
!0);if(0<h.length){var l=c[f-1],m=Hf(g);zf(l,m);0==h[0].aa&&Af(l,m)}var k=Gf(g.f,!1);0<k.length&&(m=Hf(c[f+1]),zf(g,m),0==k[0].aa&&Af(g,m))}a.pa.push(c)}},Gf=function(a,b){var c=b?"":"",d=Y[a],e=void 0===d[c]?[]:d[c];return R(e)?e:[e]},Hf=function(a){return function(){a.m()}},Kf=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Gf(a,!0);0<b.length&&f(b[0].j);e.push(a);var c=Gf(a,!1);0<c.length&&f(c[0].j)};f(d.f);b[d.f]=e}Jf(a,
b);return b},Jf=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].f,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Ja(b[e],d)){delete b[d];break}}};var Mf=function(a,b){return function(){a["9"]=b.J;a["10"]=b.I;var c=b.f,d=b.g&&b.g.ca[c],e=Ga[c]&&Ga[c].state,f=d?void 0!==d:b.Ca,g=Ga[c]&&Ga[c].firingOption,h=g&&2==g,l=g&&1==g;if((f||e&&0!=e)&&(f||h)&&(h||l))h&&Ga[c]&&1==Ga[c].state||l&&b.g&&1==b.g.ca[c]?b.J():b.I();else{var m=b.g?b.g.event:void 0;a=Lf(a,m?m.c:vb());Va(b,0);if(m){var k=a;xf(m,c)}Pa(a,b.J,b.I)}}},Lf=function(a,b){a=jf(a,b);return a},Ff=function(a,b,c){var d=new yf(b);d.g=c;zf(d,be(a));Af(d,ce(a));d.m=Mf(a,d);return d};var Rf,Sf;var ag=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=bf[b]&&jf(bf[b],c),e=d;if(d)if(d[""]&&R(d["1"]))for(var f=d["1"],e=!1,g=0;!e&&g<f.length;g++)d["1"]=f[g],e=Pa(d);else e=Pa(d);a[b]=[e,d]}return a[b]}},uf=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.C(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.C(e[d],a.c)[0])return!1;return!0},bg=!1,Nb=function(a,b,c,d){switch(b){case "gtm.js":if(bg)return!1;bg=!0;break;
case "gtm.sync":if(G("gtm.snippet")!=Ca)return!1}G("tagTypeBlacklist");for(var e={id:a,name:b,O:c||Ha,N:lf(),Y:lf(),C:ag(),c:vb()},f=[],g=0;g<tc.length;g++)if(uf(e,tc[g])){f[g]=!0;for(var h=e,l=tc[g],m=l[1],k=0;k<m.length;k++)h.N[m[k]]=!0;for(var n=l[3],k=0;k<n.length;k++)h.Y[n[k]]=!0}else f[g]=!1;xf(e);var u=[];
for(var z=0;z<Xe;z++)if(e.N[z]&&!e.Y[z])if(e.c(Y[z])){}else{u[z]=Y[z];}e.D=u;for(var t=new Bf(e),x=0;x<Xe;x++)if(e.N[x]&&!e.Y[x]&&!e.c(Y[x])){var E=e.D[x],F=Ff(E,x,t);Cf(t,x,F,E[""],
E[""],E[""]);if(E[""])break}t.addListener(e.O);for(var D=[],w=0;w<t.w.length;w++){var C=t.w[w];if(C){var y=t.wa[w],H=t.Aa[w],P=t.Da[w];if(0!=y.length||H||P){if(0<y.length)for(var X=Ef(y,C.m),V=0;V<y.length;V++)y[V]instanceof hf&&y[V].j!=w&&Df(t,y[V].j,X);(H||P)&&If(t,w)}else D.push(w)}}for(w=0;w<D.length;w++)t.w[D[w]].m();for(w=0;w<t.pa.length;w++){for(var Da=t.pa[w],aa=Da,Tc=[],Vb=0;Vb<aa.length;Vb++){var Wb=aa[Vb],Rc=Wb.f,Sc=Ga[Rc],
Tb=Sc.firingOption;0!=Tb&&(1==Tb&&void 0!==Wb.g.ca[Rc]||2==Tb&&void 0!==Sc.state)&&Tc.push(Wb)}var Ub=Kf(Tc),pb=void 0;for(pb in Ub)if(Ub.hasOwnProperty(pb)){for(var zc=void 0,He=void 0,Pb=Ub[pb],og=Pb[0],Ie=Pb[Pb.length-1],Je,pa=0;pa<aa.length;pa++){var Qb=aa[pa];!zc&&Qb.f==og&&0<pa&&(zc=aa[pa-1]);Qb.f==Ie&&pa<aa.length-1&&(He=aa[pa+1]);if(-1<Ja(Pb,Qb.f))if(Je=aa.splice(pa,1)[0],Qb.f==Ie)break;else pa--}if(Je){var Ke=Number(pb),Z=zc,Jc=He;if(Z){var pg=Z.Z[0],qg=Z.R[0],Le=Z;Le.Z=[];Le.R=[];zf(Z,pg);
Af(Z,qg)}if(Z&&Jc){var Kc=Hf(Jc);zf(Z,Kc);var Lc=Gf(Z.f,!1);0<Lc.length&&Lc[0].j!=Ke&&0==Lc[0].aa&&Af(Z,Kc);var Mc=Gf(Jc.f,!0);0<Mc.length&&Mc[0].j!=Ke&&0==Mc[0].aa&&Af(Z,Kc)}}}0<Da.length&&Da[0].m()}0<t.H||Sa(t.ka);d&&I(d)&&d({passingRules:f,resolvedTags:e.D});for(var Me in e.D)if(e.D.hasOwnProperty(Me)){var Ne=e.D[Me],Nc;if(!(Nc=void 0==Ne["5"])){var Oe=Ne["5"];Nc=!("function"!=typeof String.prototype.jb?0===Oe.indexOf("_implicit"):Oe.jb("_implicit"))}if(Nc)return!0}return!1};var cg={macro:function(a){if(af.contains(a))return af.get(a)}};cg.dataLayer=qb;cg.onHtmlSuccess=Hc(!0);cg.onHtmlFailure=Hc(!1);cg.Oa=function(){var a=A.google_tag_manager;a||(a=A.google_tag_manager={});a["GTM-PT44P2"]||(a["GTM-PT44P2"]=cg)};Ye.push.apply(Ye,function(){for(var a=[_eq,_u,'url path','path',_M(0),'/',_e,'_event',_M(1),'gtm.js','636025_1','/credits','636025_2','/securecredits.php','636025_3',_html,true,'\n\x3cscript type\x3d\x22text/gtmscript\x22\x3e(function(a,c,e,f,d,b){a.hj\x3da.hj||function(){(a.hj.q\x3da.hj.q||[]).push(arguments)};a._hjSettings\x3d{hjid:47592,hjsv:5};d\x3dc.getElementsByTagName(\x22head\x22)[0];b\x3dc.createElement(\x22script\x22);b.async\x3d1;b.src\x3de+a._hjSettings.hjid+f+a._hjSettings.hjsv;d.appendChild(b)})(window,document,\x22//static.hotjar.com/c/hotjar-\x22,\x22.js?sv\\x3d\x22);\x3c/script\x3e',2,_j,'clientid','gtm_clientid',_M(2),'48','gtm.dom','636025_4','636025_5','\x3cscript type\x3d\x22text/gtmscript\x22\x3ealert(',_E(_M(2),8,16),');\x3c/script\x3e',_T(27,28,29),4,'url','url hostname','host',_f,'referrer','event',_v,'element','gtm.element','element classes','gtm.elementClasses','element id','gtm.elementId','element target','gtm.elementTarget',_et,'element text','element url','gtm.elementUrl','history new url fragment','gtm.newUrlFragment','history old url fragment','gtm.oldUrlFragment','history new state','gtm.newHistoryState','history old state','gtm.oldHistoryState','history change source','gtm.historyChangeSource'],b=[],c=0;c<a.length;c++)b[c]=kf(c,a);return b}());nf(Ze,0,"3:0,3:1,5:2,2:3,0:4,1:5,3:6,5:7,0:8,1:9,1:11,1:13,3:15,7:16,4:17,8:18,3:19,5:20,6:21,0:22,1:23,1:24,4:30,8:31,5:32,5:33,2:34,3:35,5:36,5:37,3:38,5:39,6:40,5:41,6:42,5:43,6:44,5:45,6:46,3:47,5:48,5:49,6:50,5:51,6:52,5:53,6:54,5:55,6:56,5:57,6:58,5:59,6:60");nf($e,1,"O,AD,AAwB,CAAAB,CAAAG,AAAAY,ABAAg,AAAAAH,AAAAAZ,AAAAAhB,AAAAABG,AAAAAAY,AAAAABgB,AAAAABAG,AAAAABAY,AAAAABAgB,AAAAABAAG,AAAAABAAY");nf(bf,1,"x,BM,RQ,Rg,BAAG,BEAI");nf(Y,1,"AAP,AADw");nf(tc,2,"D:B::,G:B::,K:B::,w:C::,g:::C");nf(uc,4,"10:,12:,14:,25:,:26");
for(var dg=0;dg<Y.length;dg++){var eg=Y[dg],fg=1;eg[""]?fg=2:eg[""]&&(fg=0);Ga[dg]={firingOption:fg,state:void 0}}cg.Oa();
(function(a){})("async");
(function(){var a=v("dataLayer",[],!1),b=v("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};ka.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});gb.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Ob.push.apply(Ob,b);300<this.length;)this.shift();return cc()};Ob.push.apply(Ob,a.slice(0));q(cc)})();
if("interactive"==N.readyState&&!N.createEventObject||"complete"==N.readyState)Za();else{T(N,"DOMContentLoaded",Za);T(N,"readystatechange",Za);if(N.createEventObject&&N.documentElement.doScroll){var ng=!0;try{ng=!A.frameElement}catch(rg){}ng&&ab()}T(A,"load",Za)}"complete"===N.readyState?hb():T(A,"load",hb);
(function(a){})("async");(function(){})();var _vs="res_ts:1438952180957000,srv_cl:99744263,ds:live,cv:4";
})()
